- name: install mattermost desktop client
  block:
    - name: download mattermost .deb package
      get_url:
        url: https://releases.mattermost.com/desktop/4.5.1/mattermost-desktop-4.5.1-linux-amd64.deb
        dest: ~/Downloads/mattermost-desktop-4.5.1.deb

    - name: install mattermost desktop
      apt:
        deb: ~/Downloads/mattermost-desktop-4.5.1.deb
  become: yes

